inputs = [{"name": "E-MU XMidi1X1", "number": 1, "mono": True}, {"name": "iRig Keys", "number": 2, "mono": False}]
output = "E-MU XMidi1X1"
enable_clock = True
ignore_program_changes = False
initial_bpm = 142
tap_tempo_min_bpm = 80
tap_tempo_max_bpm = 200
bpm_offset_for_midi_cc = 70
velocity_random_offset = -40
velocity_multi_device_ctrl = True
velocity_midi_cc = 7
tempo_midi_cc = 10
chord_midi_cc = 11
route_midi_cc = 12
