inputs = [{"name": "E-MU XMidi1X1", "number": 1, "mono": True}, {"name": "iRig Keys", "number": 2, "mono": False}]
output = "E-MU XMidi1X1"
enableClock = True
ignoreProgramChanges = False
initialBpm = 142
tapTempoMinBpm = 80
tapTempoMaxBpm = 200
bpmOffsetForMidiCC = 70
velocityRandomOffset = -40
velocityMultiDeviceCtrl = True
velocityMidiCC = 7
tempoMidiCC = 10
chordMidiCC = 11
routeMidiCC = 12
